# action.yml
name: 'Action'
description: 'default action for build and test project'
inputs:
  build_type:  # id of input
    description: 'Project build type. It depends on build directory name'
    required: true
    default: 'Debug'
outputs:
  currentDir: # id of output
    description: 'current directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.build_type }}
